# Generated by Django 5.1.3 on 2025-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hgnc_id", models.CharField(max_length=255, unique=True)),
                (
                    "symbol",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "locus_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("locus_type", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("alias_symbol", models.TextField(blank=True, null=True)),
                ("prev_symbol", models.TextField(blank=True, null=True)),
                ("gene_group", models.TextField(blank=True, null=True)),
                ("entrez_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ensembl_gene_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
