# Generated by Django 5.2.3 on 2025-06-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primerpair',
            old_name='f_GC_pct',
            new_name='f_gc_pct',
        ),
        migrations.RenameField(
            model_name='primerpair',
            old_name='f_Tm_C',
            new_name='f_tm_C',
        ),
        migrations.RenameField(
            model_name='primerpair',
            old_name='r_GC_pct',
            new_name='r_gc_pct',
        ),
        migrations.RenameField(
            model_name='primerpair',
            old_name='r_Tm_C',
            new_name='r_tm_C',
        ),
    ]
