# Generated by Django 5.2.3 on 2025-06-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0003_rename_f_gc_pct_primerpair_f_gc_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerpair',
            name='f_inv_pmcid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='f_inv_pmcid_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='f_reg_pmcid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='f_reg_pmcid_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='pair_shared_pmcid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='r_inv_pmcid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='r_inv_pmcid_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='r_reg_pmcid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='r_reg_pmcid_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='primerpair',
            name='f_gene',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='primerpair',
            name='r_gene',
            field=models.CharField(max_length=40),
        ),
    ]
