# Generated by Django 5.2.3 on 2025-06-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0004_primerpair_f_inv_pmcid_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerpair',
            name='pair_shared_pmcid_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
