# Generated by Django 5.2.3 on 2025-06-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0005_primerpair_pair_shared_pmcid_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='primerpair',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='primerpair',
            name='species',
            field=models.CharField(db_index=True, default='human', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='primerpair',
            unique_together={('species', 'gene', 'f_sequence', 'r_sequence')},
        ),
    ]
