# Generated by Django 5.1.3 on 2025-06-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "primers",
            "0006_alter_primerpair_unique_together_primerpair_species_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_0",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_0_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_1",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_1_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_2",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_2_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_3",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_3_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_4",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_cross_specificity_4_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_0",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_0_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_1",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_1_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_2",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_2_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_3",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_3_seq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_4",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_cross_specificity_4_seq",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
