# Generated by Django 5.1.3 on 2025-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primers", "0007_primerpair_f_cross_specificity_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primerpair",
            name="biophysics_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="evidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_GC_pct",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_Tm_C",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_evalue",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_match_end",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_match_start",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_occurrence_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_orientation",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_pmcid_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_self_comp",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="f_total_citations",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="pair_comp",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="pickr_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_GC_pct",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_Tm_C",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_evalue",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_match_end",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_match_start",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_occurrence_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_orientation",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_pmcid_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_self_comp",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="r_total_citations",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="primerpair",
            name="synergy_score",
            field=models.FloatField(default=0.0),
        ),
    ]
