# Generated by Django 5.1.3 on 2025-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primers", "0008_alter_primerpair_biophysics_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="primerpair",
            name="percentile",
            field=models.FloatField(default=0.0),
        ),
    ]
