# Generated by Django 5.1.3 on 2025-07-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primers", "0009_primerpair_percentile"),
    ]

    operations = [
        migrations.AddField(
            model_name="primerpair",
            name="f_found",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="f_found_list",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_found",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="primerpair",
            name="r_found_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
