# Generated by Django 5.1.3 on 2025-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primers", "0010_primerpair_f_found_primerpair_f_found_list_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("species", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Gene Symbol",
                "verbose_name_plural": "Gene Symbols",
                "unique_together": {("symbol", "species")},
            },
        ),
    ]
