from django.db import models
from django.contrib.postgres.fields import ArrayField

class PrimerPair(models.Model):
    gene = models.CharField(max_length=32, db_index=True)       # your CSV filename
    f_sequence = models.CharField(max_length=255)
    r_sequence = models.CharField(max_length=255)
    f_gene = models.CharField(max_length=32)
    r_gene = models.CharField(max_length=32)
    f_author_gene_list = ArrayField(models.CharField(max_length=32), blank=True, default=list)
    r_author_gene_list = ArrayField(models.CharField(max_length=32), blank=True, default=list)
    f_evalue = models.FloatField()
    r_evalue = models.FloatField()
    f_occurrence_count = models.IntegerField()
    r_occurrence_count = models.IntegerField()
    f_pmcid_list = ArrayField(models.IntegerField(), blank=True, default=list)
    r_pmcid_list = ArrayField(models.IntegerField(), blank=True, default=list)
    f_Tm_C = models.FloatField()
    r_Tm_C = models.FloatField()
    f_GC_pct = models.FloatField()
    r_GC_pct = models.FloatField()
    f_total_citations = models.IntegerField()
    r_total_citations = models.IntegerField()
    f_pmcid_count = models.IntegerField()
    r_pmcid_count = models.IntegerField()
    f_match_start = models.IntegerField()
    r_match_start = models.IntegerField()
    f_match_end = models.IntegerField()
    r_match_end = models.IntegerField()
    f_orientation = models.CharField(max_length=8)
    r_orientation = models.CharField(max_length=8)
    f_self_comp = models.FloatField()
    r_self_comp = models.FloatField()
    pair_comp = models.FloatField()
    evidence_score = models.FloatField()
    biophysics_score = models.FloatField()
    synergy_score = models.FloatField()
    pickr_score = models.FloatField()

    class Meta:
        unique_together = (('gene','f_sequence','r_sequence'),)
        ordering = ('-pickr_score',)
